class cardModel {
  String ID,
      boxID,
      cardID,
      cardImage,
      cardColor,
      cardName,
      cardType,
      cardFullCos,
      cardMaincos,
      cardSubCos,
      cardSpeed,
      cardPower,
      cardHit,
      cardCognomen,
      cardClan,
      cardSkill;

  cardModel(
      {required this.ID,
      required this.boxID,
      required this.cardID,
      required this.cardImage,
      required this.cardName,
      required this.cardColor,
      required this.cardType,
      required this.cardFullCos,
      required this.cardMaincos,
      required this.cardSubCos,
      required this.cardSpeed,
      required this.cardPower,
      required this.cardHit,
      required this.cardCognomen,
      required this.cardClan,
      required this.cardSkill});
}
